export const courtImages: { [key: string]: number } = {
  "/boramae_1.jpg": require("../../assets/courts/boramae_1.jpg"),
  "/children_park_1.jpg": require("../../assets/courts/children_park_1.jpg"),
  "/dream_forest.jpg": require("../../assets/courts/dream_forest.jpg"),
  "/hangang_1.jpg": require("../../assets/courts/hangang_1.jpg"),
  "/hangang_2.jpg": require("../../assets/courts/hangang_2.jpg"),
  "/noeul_1.jpg": require("../../assets/courts/noeul_1.jpg"),
  "/noeul_2.jpg": require("../../assets/courts/noeul_2.jpg"),
  "/olympic_park_1.jpg": require("../../assets/courts/olympic_park_1.jpg"),
  "/olympic_park_3.jpg": require("../../assets/courts/olympic_park_3.jpg"),
  "/olympic_park_2.jpg": require("../../assets/courts/olympic_park_2.jpg"),
  "/sangam_1.jpg": require("../../assets/courts/sangam_1.jpg"),
  "/sangam_2.jpg": require("../../assets/courts/sangam_2.jpg"),
  "/seoul_forest_1.jpg": require("../../assets/courts/seoul_forest_1.jpg"),
  "/seoul_forest_2.jpg": require("../../assets/courts/seoul_forest_2.jpg"),
  "/yongsan_1.jpg": require("../../assets/courts/yongsan_1.jpg"),
  "/yongsan_2.jpg": require("../../assets/courts/yongsan_2.jpg"),
};
