import { Post } from "../types/match";

const DUMMY_POSTS: Post[] = [
  {
    id: 1,
    title: "주말 농구 한 판 하실 분!",
    courtName: "올림픽공원 농구장",
    location: "송파구",
    date: "2025-01-20",
    time: "14:00",
    level: "INTERMEDIATE",
    currentPlayers: 8,
    maxPlayers: 10,
    cost: 5000,
    status: "OPEN",
    description: "주말 오후에 농구하실 분들 모집합니다. 중급 이상 실력자 환영!",
  },
  {
    id: 2,
    title: "평일 저녁 친선경기",
    courtName: "강남구민체육센터",
    location: "강남구",
    date: "2025-01-18",
    time: "19:30",
    level: "BEGINNER",
    currentPlayers: 6,
    maxPlayers: 10,
    cost: 0,
    status: "OPEN",
    description: "초보자도 환영합니다. 재미있게 즐기면서 해요!",
  },
  {
    id: 3,
    title: "실력자 모집합니다",
    courtName: "마포구민체육센터",
    location: "마포구",
    date: "2025-01-19",
    time: "16:00",
    level: "ADVANCED",
    currentPlayers: 10,
    maxPlayers: 10,
    cost: 10000,
    status: "CLOSED",
    description: "상급자 위주로 진행되는 경기입니다.",
  },
  {
    id: 4,
    title: "아침 농구 모임",
    courtName: "서초실내체육관",
    location: "서초구",
    date: "2025-01-21",
    time: "07:00",
    level: "INTERMEDIATE",
    currentPlayers: 4,
    maxPlayers: 8,
    cost: 8000,
    status: "OPEN",
    description: "아침 운동하실 분들 모집합니다!",
  },
  {
    id: 5,
    title: "주말 초보자 모임",
    courtName: "노원구민체육센터",
    location: "노원구",
    date: "2025-01-22",
    time: "10:00",
    level: "BEGINNER",
    currentPlayers: 6,
    maxPlayers: 8,
    cost: 5000,
    status: "OPEN",
    description: "농구 배우고 싶으신 분들 환영합니다.",
  },
];

export { DUMMY_POSTS };
